[project]
name = "anime-calendar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ics>=0.7.2",
    "requests>=2.32.4",
    "tzdata>=2025.2",
]
