name: Weekly Calendar Update

on:
  schedule:
    - cron: '* * * * *'  # 每周一 8:00 UTC
  workflow_dispatch:

jobs:
  update-calendar:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'  # UV 支持使用 pip 的缓存目录

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: |
          uv pip sync

      - name: Run calendar generator
        run: python main.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add dist/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update calendar files [skip ci]" && git push)
