name: Weekly Calendar Update

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  update-calendar:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.5'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run calendar generator
        run: python main.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add dist/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update calendar files [skip ci]" && git push)
